### PR TITLE
Fix #47: Not able to inject a custom schema service

### LINKED ISSUE #47: Not able to inject a custom schema service
tl;dr

Can't Change or initialize the `graphql.schema` service even through compiler pass.

PR: https://github.com/Youshido/GraphQLBundle/pull/48

Hi 

First of all, thanks for all the work in GraphQL and GraphQLBundle.

I'm currently trying to inject the Fields into the Schema.
So for that, I can't simply rely on the config `graphql.schema_class` since the initialization is also needed.
Because of that I've attempted to override the `graphql.schema` service, and due to the way Symfony works, when there is a duplicated service it ignores/picks one, so since the service is already defined in this [`services.xml`](https://github.com/Youshido/GraphQLBundle/blob/5d17ce4ef7064e875bcf4e07d84ffd4b9859b2b2//Resources/config/services.xml#L14) so a compiler pass is needed.

Then I've tried simply to make a compiler pass with:
```php
$container->set('graphql.schema', $container->get('acme.graphql.schema'));
```

Although even if the service is initialized, [there is a class check](https://github.com/Youshido/GraphQLBundle/blob/5d17ce4ef7064e875bcf4e07d84ffd4b9859b2b2/Controller/GraphQLController.php#L42) that will fail since the service is initialized without the class name and [initializes the class anyway](https://github.com/Youshido/GraphQLBundle/blob/5d17ce4ef7064e875bcf4e07d84ffd4b9859b2b2/Controller/GraphQLController.php#L45)

Bonus, even if we define the service, we [MUST define the schema class](https://github.com/Youshido/GraphQLBundle/blob/5d17ce4ef7064e875bcf4e07d84ffd4b9859b2b2//Controller/GraphQLController.php#L37) which is not relevant.

I am not a Symfony expert, if I'm missing or doing something wrong please tell me.

I'll make a PR for this issue

### PR DESCRIPTION
**Pull request by mloureiro**
This PR attempts to fix #47 

By adding a new optional configuration parameter ([`graphql.schema_service`](https://github.com/MLoureiro/GraphQLBundle/blob/8ddd8ada484749af28927426b263506491b69894/DependencyInjection/Configuration.php#L27)) and improving the way to [load the service](https://github.com/MLoureiro/GraphQLBundle/blob/8ddd8ada484749af28927426b263506491b69894/Controller/GraphQLController.php#L136).

No tests were added since there are none.

### CODE REVIEW

**Comment by seb2411** [comment]
Any plan to merge this PR ?

**Comment by viniychuk** [comment]
@MLoureiro @seb2411 We merged this PR but we're going to replace it with a new logic that would support only Service type of schema injection and we'll move all the logic from the controller to the bundle internal class. `schema_service` name of config will remain intact though.

**Comment by iainmckay** [comment]
Could you tag a new version for this?

File: Controller/GraphQLController.php [hunk 1]
```diff
@@ -132,4 +123,63 @@ private function getPayload()
...
+        if ($this->container->initialized('graphql.schema')) {
+            return;
+        }
+
+        $this->container->set('graphql.schema', $this->makeSchemaService());
+    }
+
+    private function makeSchemaService()
+    {
+        if ($this->container->has($this->getSchemaService())) {
```
Comment (SebastienTainon) [inline Controller/GraphQLController.php:138]: here if $this->getSchemaService returns `null` because the schemaService is not defined, it can create bugs within Symfony trying to get the "null" service. Could you add a check of non-nullity please?
